const router = require('express').Router();
const c = require('../../../controller/product-controllers/box-controller');
const { protect, restrictTo } = require('../../../middleware/auth-middleware');
const { validate } = require('../../../middleware/validate');
const { validateParam } = require('../../../middleware/validate-param');
const { productIdSchema } = require('../../../validation/product-validations/product-validation');
const { createBoxSchema, editBoxSchema } = require('../../../validation/product-validations/box-validation');
const { uploadImage } = require('../../../middleware/upload-image');
const { uploadCatalogImages, editCatalogImages } = require('../../../controller/product-controllers/catalog-images-controller');
router.get('/all', protect, restrictTo('admin'), c.list(true));
router.get('/admin/:boxId', protect, restrictTo('admin'), validateParam('boxId', productIdSchema), c.get(true));
router.get('/', c.list(false));
router.get('/slug/:slug', c.get(false));
router.get('/id/:boxId', validateParam('boxId', productIdSchema), c.get(false));
router.use(protect, restrictTo('admin'));
router.post('/', validate(createBoxSchema), c.create);
router.patch('/:boxId', validateParam('boxId', productIdSchema), validate(editBoxSchema), c.edit);
router.delete('/:boxId', validateParam('boxId', productIdSchema), c.remove);
router.post('/:boxId/images', validateParam('boxId', productIdSchema), uploadImage.array('images', 10), uploadCatalogImages('Box'));
router.put('/:boxId/images', validateParam('boxId', productIdSchema), validate(require('joi').object({ images: require('joi').array().max(10).unique().items(require('joi').string()).required(), coverImage: require('joi').string() }).unknown(false)), editCatalogImages('Box'));
module.exports = router;
